from __future__ import annotations

from pathlib import Path

TOOL_NAME = "aos-clientsync"
BACKEND_NAME = "clientsync-api"
DEFAULT_API_URL = "https://api.clientsync.io/v1"
CLIENTSYNC_API_KEY_ENV = "CLIENTSYNC_API_KEY"
CLIENTSYNC_API_URL_ENV = "CLIENTSYNC_API_URL"
CLIENTSYNC_CLIENT_ID_ENV = "CLIENTSYNC_CLIENT_ID"
CLIENTSYNC_TICKET_ID_ENV = "CLIENTSYNC_TICKET_ID"
CLIENTSYNC_TECHNICIAN_ID_ENV = "CLIENTSYNC_TECHNICIAN_ID"
CLIENTSYNC_COMPLIANCE_ID_ENV = "CLIENTSYNC_COMPLIANCE_ID"
CLIENTSYNC_SLA_ID_ENV = "CLIENTSYNC_SLA_ID"
CLIENTSYNC_REPORT_TYPE_ENV = "CLIENTSYNC_REPORT_TYPE"

MODE_ORDER = ["readonly", "write", "full", "admin"]
HARNESS_ROOT = Path(__file__).resolve().parents[2]
CONNECTOR_PATH = HARNESS_ROOT.parent / "connector.json"
PERMISSIONS_PATH = HARNESS_ROOT / "permissions.json"
