from __future__ import annotations

from pathlib import Path

TOOL_NAME = "aos-coderabbit"
BACKEND_NAME = "coderabbit-api"

CODERABBIT_API_KEY_ENV = "CODERABBIT_API_KEY"
CODERABBIT_BASE_URL_ENV = "CODERABBIT_BASE_URL"
CODERABBIT_REPO_ENV = "CODERABBIT_REPO"
CODERABBIT_PR_NUMBER_ENV = "CODERABBIT_PR_NUMBER"
CODERABBIT_REVIEW_ID_ENV = "CODERABBIT_REVIEW_ID"
CODERABBIT_CONFIG_PATH_ENV = "CODERABBIT_CONFIG_PATH"
CODERABBIT_STATE_PATH_ENV = "CODERABBIT_STATE_PATH"
CODERABBIT_REPORT_START_DATE_ENV = "CODERABBIT_REPORT_START_DATE"
CODERABBIT_REPORT_END_DATE_ENV = "CODERABBIT_REPORT_END_DATE"
CODERABBIT_REPORT_LIMIT_ENV = "CODERABBIT_REPORT_LIMIT"
CODERABBIT_REPORT_CURSOR_ENV = "CODERABBIT_REPORT_CURSOR"
CODERABBIT_REPORT_TEMPLATE_ENV = "CODERABBIT_REPORT_TEMPLATE"
CODERABBIT_REPORT_PROMPT_ENV = "CODERABBIT_REPORT_PROMPT"
CODERABBIT_REVIEW_KIND_ENV = "CODERABBIT_REVIEW_KIND"
CODERABBIT_CONFIG_CONTENT_ENV = "CODERABBIT_CONFIG_CONTENT"

DEFAULT_BASE_URL = "https://api.coderabbit.ai"
DEFAULT_CONFIG_FILENAME = ".coderabbit.yaml"
DEFAULT_STATE_FILENAME = ".coderabbit.review-state.json"

MODE_ORDER = ["readonly", "write", "full", "admin"]

HARNESS_ROOT = Path(__file__).resolve().parents[2]
CONNECTOR_PATH = HARNESS_ROOT.parent / "connector.json"
PERMISSIONS_PATH = HARNESS_ROOT / "permissions.json"
