from __future__ import annotations

from pathlib import Path

TOOL_NAME = "aos-discord-workflow"
BACKEND_NAME = "discord-bot-api"

DISCORD_BOT_TOKEN_ENV = "DISCORD_BOT_TOKEN"
DISCORD_API_BASE_URL_ENV = "DISCORD_API_BASE_URL"
DISCORD_GUILD_ID_ENV = "DISCORD_GUILD_ID"
DISCORD_CHANNEL_ID_ENV = "DISCORD_CHANNEL_ID"
DISCORD_MESSAGE_ID_ENV = "DISCORD_MESSAGE_ID"
DISCORD_WEBHOOK_URL_ENV = "DISCORD_WEBHOOK_URL"
DISCORD_CONTENT_ENV = "DISCORD_CONTENT"
DISCORD_EMBED_JSON_ENV = "DISCORD_EMBED_JSON"
DISCORD_ROLE_ID_ENV = "DISCORD_ROLE_ID"
DISCORD_MEMBER_ID_ENV = "DISCORD_MEMBER_ID"
DISCORD_THREAD_NAME_ENV = "DISCORD_THREAD_NAME"
DISCORD_CHANNEL_NAME_ENV = "DISCORD_CHANNEL_NAME"
DISCORD_REACTION_ENV = "DISCORD_REACTION"

DEFAULT_API_BASE_URL = "https://discord.com/api/v10"
MODE_ORDER = ["readonly", "write", "full", "admin"]

HARNESS_ROOT = Path(__file__).resolve().parents[2]
CONNECTOR_PATH = HARNESS_ROOT.parent / "connector.json"
PERMISSIONS_PATH = HARNESS_ROOT / "permissions.json"
