from __future__ import annotations

MODE_ORDER = ["readonly", "write", "full", "admin"]
MANIFEST_SCHEMA_VERSION = "1.0.0"
TOOL_NAME = "aos-stripe"
BACKEND_NAME = "stripe-api"
DEFAULT_API_BASE_URL = "https://api.stripe.com"

STRIPE_SECRET_KEY_ENV = "STRIPE_SECRET_KEY"
STRIPE_WEBHOOK_SECRET_ENV = "STRIPE_WEBHOOK_SECRET"
STRIPE_ACCOUNT_ID_ENV = "STRIPE_ACCOUNT_ID"
STRIPE_CUSTOMER_ID_ENV = "STRIPE_CUSTOMER_ID"
STRIPE_CUSTOMER_EMAIL_ENV = "STRIPE_CUSTOMER_EMAIL"
STRIPE_PAYMENT_INTENT_ID_ENV = "STRIPE_PAYMENT_INTENT_ID"
STRIPE_SUBSCRIPTION_ID_ENV = "STRIPE_SUBSCRIPTION_ID"
STRIPE_PRICE_ID_ENV = "STRIPE_PRICE_ID"
STRIPE_INVOICE_ID_ENV = "STRIPE_INVOICE_ID"
