from __future__ import annotations

TOOL_NAME = "aos-buffer"
BACKEND_NAME = "buffer-rest-api"
MANIFEST_VERSION = "1.0.0"
DEFAULT_BASE_URL = "https://api.bufferapp.com/1"
DEFAULT_GRAPHQL_URL = "https://api.buffer.com"
DEFAULT_TIMEOUT_SECONDS = 20
ENV_API_KEYS = ("BUFFER_API_KEY", "BUFFER_ACCESS_TOKEN")
ENV_BASE_URL = "BUFFER_BASE_URL"
ENV_GRAPHQL_URL = "BUFFER_GRAPHQL_URL"
ENV_ACCOUNT_ID = "BUFFER_ACCOUNT_ID"
ENV_CHANNEL_ID = "BUFFER_CHANNEL_ID"
ENV_PROFILE_ID = "BUFFER_PROFILE_ID"
ENV_POST_ID = "BUFFER_POST_ID"
ENV_POST_TEXT = "BUFFER_POST_TEXT"
