from __future__ import annotations

from pathlib import Path

TOOL_NAME = "aos-anthropic"
BACKEND_NAME = "anthropic-api"

ANTHROPIC_API_KEY_ENV = "ANTHROPIC_API_KEY"
ANTHROPIC_BASE_URL_ENV = "ANTHROPIC_BASE_URL"
ANTHROPIC_VERSION_ENV = "ANTHROPIC_VERSION"
ANTHROPIC_MODEL_ENV = "ANTHROPIC_MODEL"
ANTHROPIC_SYSTEM_PROMPT_ENV = "ANTHROPIC_SYSTEM_PROMPT"
ANTHROPIC_MESSAGES_JSON_ENV = "ANTHROPIC_MESSAGES_JSON"
ANTHROPIC_MAX_TOKENS_ENV = "ANTHROPIC_MAX_TOKENS"
ANTHROPIC_TEMPERATURE_ENV = "ANTHROPIC_TEMPERATURE"
ANTHROPIC_THINKING_BUDGET_ENV = "ANTHROPIC_THINKING_BUDGET"

DEFAULT_BASE_URL = "https://api.anthropic.com"
DEFAULT_VERSION = "2023-06-01"
MODE_ORDER = ["readonly", "write", "full", "admin"]

HARNESS_ROOT = Path(__file__).resolve().parents[2]
CONNECTOR_PATH = HARNESS_ROOT.parent / "connector.json"
PERMISSIONS_PATH = HARNESS_ROOT / "permissions.json"
