export const browserCoreExamples = [
  "argent browser status",
  "argent browser start",
  "argent browser stop",
  "argent browser tabs",
  "argent browser open https://example.com",
  "argent browser focus abcd1234",
  "argent browser close abcd1234",
  "argent browser screenshot",
  "argent browser screenshot --full-page",
  "argent browser screenshot --ref 12",
  "argent browser snapshot",
  "argent browser snapshot --format aria --limit 200",
  "argent browser snapshot --efficient",
  "argent browser snapshot --labels",
];

export const browserActionExamples = [
  "argent browser navigate https://example.com",
  "argent browser resize 1280 720",
  "argent browser click 12 --double",
  'argent browser type 23 "hello" --submit',
  "argent browser press Enter",
  "argent browser hover 44",
  "argent browser drag 10 11",
  "argent browser select 9 OptionA OptionB",
  "argent browser upload /tmp/file.pdf",
  'argent browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "argent browser dialog --accept",
  'argent browser wait --text "Done"',
  "argent browser evaluate --fn '(el) => el.textContent' --ref 7",
  "argent browser console --level error",
  "argent browser pdf",
];
