from __future__ import annotations

from pathlib import Path

TOOL_NAME = "aos-slack-workflow"
BACKEND_NAME = "slack-web-api"

SLACK_BOT_TOKEN_ENV = "SLACK_BOT_TOKEN"
SLACK_APP_TOKEN_ENV = "SLACK_APP_TOKEN"
SLACK_CHANNEL_ID_ENV = "SLACK_CHANNEL_ID"
SLACK_THREAD_TS_ENV = "SLACK_THREAD_TS"
SLACK_TEXT_ENV = "SLACK_TEXT"
SLACK_EMOJI_ENV = "SLACK_EMOJI"
SLACK_USER_ID_ENV = "SLACK_USER_ID"
SLACK_CHANNEL_NAME_ENV = "SLACK_CHANNEL_NAME"
SLACK_CANVAS_ID_ENV = "SLACK_CANVAS_ID"
SLACK_CANVAS_TITLE_ENV = "SLACK_CANVAS_TITLE"
SLACK_CANVAS_CONTENT_ENV = "SLACK_CANVAS_CONTENT"
SLACK_CANVAS_CHANGES_ENV = "SLACK_CANVAS_CHANGES"
SLACK_FILE_PATH_ENV = "SLACK_FILE_PATH"
SLACK_FILE_TITLE_ENV = "SLACK_FILE_TITLE"
SLACK_REMINDER_TEXT_ENV = "SLACK_REMINDER_TEXT"
SLACK_REMINDER_TIME_ENV = "SLACK_REMINDER_TIME"
SLACK_REMINDER_USER_ENV = "SLACK_REMINDER_USER"
SLACK_BASE_URL_ENV = "SLACK_BASE_URL"

DEFAULT_BASE_URL = "https://slack.com/api"
MODE_ORDER = ["readonly", "write", "full", "admin"]

HARNESS_ROOT = Path(__file__).resolve().parents[2]
CONNECTOR_PATH = HARNESS_ROOT.parent / "connector.json"
PERMISSIONS_PATH = HARNESS_ROOT / "permissions.json"
