from __future__ import annotations

from pathlib import Path

TOOL_NAME = "aos-pinecone"
BACKEND_NAME = "pinecone-api"
DEFAULT_CONTROL_BASE_URL = "https://api.pinecone.io"
DEFAULT_API_VERSION = "2025-10"
MODE_ORDER = ["readonly", "write", "full", "admin"]

PINECONE_API_KEY_ENV = "PINECONE_API_KEY"
PINECONE_API_BASE_URL_ENV = "PINECONE_API_BASE_URL"
PINECONE_API_VERSION_ENV = "PINECONE_API_VERSION"
PINECONE_INDEX_NAME_ENV = "PINECONE_INDEX_NAME"
PINECONE_INDEX_HOST_ENV = "PINECONE_INDEX_HOST"
PINECONE_NAMESPACE_ENV = "PINECONE_NAMESPACE"
PINECONE_VECTOR_ID_ENV = "PINECONE_VECTOR_ID"
PINECONE_INDEX_DIMENSION_ENV = "PINECONE_INDEX_DIMENSION"
PINECONE_METRIC_ENV = "PINECONE_METRIC"
PINECONE_CLOUD_ENV = "PINECONE_CLOUD"
PINECONE_REGION_ENV = "PINECONE_REGION"
PINECONE_INDEX_LIMIT_ENV = "PINECONE_INDEX_LIMIT"
PINECONE_TOP_K_ENV = "PINECONE_TOP_K"

HARNESS_ROOT = Path(__file__).resolve().parents[2]
CONNECTOR_PATH = HARNESS_ROOT.parent / "connector.json"
PERMISSIONS_PATH = HARNESS_ROOT / "permissions.json"
