from __future__ import annotations

from pathlib import Path

TOOL_NAME = "aos-dropbox"
BACKEND_NAME = "dropbox-api"

DROPBOX_APP_KEY_ENV = "DROPBOX_APP_KEY"
DROPBOX_APP_SECRET_ENV = "DROPBOX_APP_SECRET"
DROPBOX_REFRESH_TOKEN_ENV = "DROPBOX_REFRESH_TOKEN"
DROPBOX_PATH_ENV = "DROPBOX_PATH"
DROPBOX_FILE_ID_ENV = "DROPBOX_FILE_ID"
DROPBOX_QUERY_ENV = "DROPBOX_QUERY"
DROPBOX_CURSOR_ENV = "DROPBOX_CURSOR"
DROPBOX_SHARED_LINK_SETTINGS_ENV = "DROPBOX_SHARED_LINK_SETTINGS"
DROPBOX_SOURCE_FILE_ENV = "DROPBOX_SOURCE_FILE"
DROPBOX_DEST_PATH_ENV = "DROPBOX_DEST_PATH"
DROPBOX_OUTPUT_FILE_ENV = "DROPBOX_OUTPUT_FILE"
DROPBOX_LIMIT_ENV = "DROPBOX_LIMIT"
DROPBOX_BASE_URL_ENV = "DROPBOX_BASE_URL"
DROPBOX_CONTENT_URL_ENV = "DROPBOX_CONTENT_URL"

DEFAULT_API_BASE_URL = "https://api.dropboxapi.com"
DEFAULT_CONTENT_BASE_URL = "https://content.dropboxapi.com"
MODE_ORDER = ["readonly", "write", "full", "admin"]

HARNESS_ROOT = Path(__file__).resolve().parents[2]
CONNECTOR_PATH = HARNESS_ROOT.parent / "connector.json"
PERMISSIONS_PATH = HARNESS_ROOT / "permissions.json"
