from __future__ import annotations

from pathlib import Path

TOOL_NAME = "aos-canva"
BACKEND_NAME = "canva-api"
API_BASE_URL = "https://api.canva.com/rest/v1"
MODE_ORDER = ["readonly", "write", "admin"]

PACKAGE_ROOT = Path(__file__).resolve().parent
HARNESS_ROOT = PACKAGE_ROOT.parents[1]
CONNECTOR_ROOT = HARNESS_ROOT.parent
CONNECTOR_PATH = CONNECTOR_ROOT / "connector.json"
PERMISSIONS_PATH = HARNESS_ROOT / "permissions.json"

CANVA_API_KEY_ENV = "CANVA_API_KEY"
CANVA_FOLDER_ID_ENV = "CANVA_FOLDER_ID"
CANVA_DESIGN_ID_ENV = "CANVA_DESIGN_ID"
CANVA_TEMPLATE_ID_ENV = "CANVA_TEMPLATE_ID"
CANVA_BRAND_TEMPLATE_ID_ENV = "CANVA_BRAND_TEMPLATE_ID"
CANVA_EXPORT_FORMAT_ENV = "CANVA_EXPORT_FORMAT"
CANVA_EXPORT_JOB_ID_ENV = "CANVA_EXPORT_JOB_ID"
CANVA_ASSET_FILE_ENV = "CANVA_ASSET_FILE"
CANVA_ASSET_URL_ENV = "CANVA_ASSET_URL"
CANVA_ASSET_NAME_ENV = "CANVA_ASSET_NAME"
CANVA_ASSET_ID_ENV = "CANVA_ASSET_ID"
CANVA_AUTOFILL_DATA_ENV = "CANVA_AUTOFILL_DATA"
CANVA_FOLDER_NAME_ENV = "CANVA_FOLDER_NAME"
CANVA_TITLE_ENV = "CANVA_DESIGN_TITLE"
