/**
 * Onboarding provider cards — auto-generated.
 *
 * AUTO-GENERATED by scripts/export-provider-catalog.ts from
 * src/agents/provider-registry-seed.ts during `pnpm build`.
 * Do not edit by hand — your changes will be overwritten.
 *
 * The dashboard SetupWizard reads this via
 * dashboard/src/lib/onboardingStack.ts so the wizard cards stay in
 * lockstep with the core provider-registry seed (see issue #295).
 */

export type OnboardingProviderCardSeed = {
  id: string;
  label: string;
  accent: string;
  recommended: string;
  description: string;
  keyUrl: string;
  onboardingVisible: true;
};

export const ONBOARDING_PROVIDER_CARD_SEED_VERSION = 10;
export const ONBOARDING_PROVIDER_CARD_SEEDS: ReadonlyArray<OnboardingProviderCardSeed> = [
  {
    id: "anthropic",
    label: "Anthropic",
    accent: "amber",
    recommended: "Best Claude experience",
    description:
      "Claude models with strong coding and reasoning. Best if you already use Anthropic or Claude Max.",
    keyUrl: "https://console.anthropic.com/",
    onboardingVisible: true,
  },
  {
    id: "openai",
    label: "OpenAI",
    accent: "emerald",
    recommended: "Balanced hosted default",
    description:
      "GPT models plus built-in TTS pairing. Great low-friction path if you already have an OpenAI API account.",
    keyUrl: "https://platform.openai.com/api-keys",
    onboardingVisible: true,
  },
  {
    id: "minimax",
    label: "MiniMax",
    accent: "violet",
    recommended: "Great value + media stack",
    description:
      "Fast, affordable hosted models with broad media capabilities. Good when you want one provider for a lot of AI surface area.",
    keyUrl: "https://platform.minimaxi.com/",
    onboardingVisible: true,
  },
  {
    id: "zai",
    label: "Z.AI / GLM",
    accent: "cyan",
    recommended: "Strong GLM family",
    description:
      "GLM hosted models from Z.AI. Best if you specifically want the GLM family or already use bigmodel.cn.",
    keyUrl: "https://open.bigmodel.cn/",
    onboardingVisible: true,
  },
  {
    id: "local",
    label: "Local only",
    accent: "slate",
    recommended: "No hosted keys",
    description:
      "Use local models only. Best if you are intentionally staying offline or already run Ollama/LM Studio locally.",
    keyUrl: "https://ollama.com/",
    onboardingVisible: true,
  },
];
