from __future__ import annotations

from pathlib import Path

TOOL_NAME = "aos-openai"
BACKEND_NAME = "openai-api"

OPENAI_API_KEY_ENV = "OPENAI_API_KEY"
OPENAI_ORG_ID_ENV = "OPENAI_ORG_ID"
OPENAI_PROJECT_ID_ENV = "OPENAI_PROJECT_ID"
OPENAI_BASE_URL_ENV = "OPENAI_BASE_URL"
OPENAI_MODEL_ENV = "OPENAI_MODEL"
OPENAI_PROMPT_ENV = "OPENAI_PROMPT"
OPENAI_MESSAGES_JSON_ENV = "OPENAI_MESSAGES_JSON"
OPENAI_MAX_TOKENS_ENV = "OPENAI_MAX_TOKENS"
OPENAI_TEMPERATURE_ENV = "OPENAI_TEMPERATURE"
OPENAI_IMAGE_PROMPT_ENV = "OPENAI_IMAGE_PROMPT"
OPENAI_IMAGE_SIZE_ENV = "OPENAI_IMAGE_SIZE"
OPENAI_IMAGE_FILE_ENV = "OPENAI_IMAGE_FILE"
OPENAI_AUDIO_FILE_ENV = "OPENAI_AUDIO_FILE"
OPENAI_VOICE_ENV = "OPENAI_VOICE"

DEFAULT_BASE_URL = "https://api.openai.com/v1"
MODE_ORDER = ["readonly", "write", "full", "admin"]

HARNESS_ROOT = Path(__file__).resolve().parents[2]
CONNECTOR_PATH = HARNESS_ROOT.parent / "connector.json"
PERMISSIONS_PATH = HARNESS_ROOT / "permissions.json"
