#!/usr/bin/env tsx
/**
 * Generate dashboard/provider-catalog/index.cjs from the canonical
 * TypeScript seed at src/agents/provider-registry-seed.ts.
 *
 * The dashboard API server (`dashboard/api-server.cjs`) is shipped as
 * CommonJS and `require()`s `./provider-catalog/index.cjs` as its
 * provider-registry fallback. When `~/.argentos/provider-registry.json`
 * is absent (fresh CI, headless dashboard start, dashboard launched
 * before the CLI ran), the fallback is the only source of providers —
 * an empty fallback yields a blank Models page.
 *
 * Keeping the .cjs hand-authored guarantees drift from the TS seed
 * (see #268). This script makes the .cjs a build artifact derived from
 * the TS seed, so the two stay in lockstep.
 *
 * Wired into `pnpm build` ahead of `tsdown` so the regenerated file is
 * always present in the working tree at install time.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SEED_VERSION, buildSeedRegistry } from "../src/agents/provider-registry-seed.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, "..");
const outputPath = path.join(projectRoot, "dashboard", "provider-catalog", "index.cjs");

function exportProviderCatalog(): void {
  const registry = buildSeedRegistry();
  const providerCount = Object.keys(registry.providers ?? {}).length;

  if (providerCount === 0) {
    throw new Error(
      "[export-provider-catalog] buildSeedRegistry() returned 0 providers — refusing to write empty fallback",
    );
  }

  const banner = [
    '"use strict";',
    "",
    "/**",
    " * Dashboard API provider registry seed fallback.",
    " *",
    " * AUTO-GENERATED by scripts/export-provider-catalog.ts from",
    " * src/agents/provider-registry-seed.ts during `pnpm build`.",
    " * Do not edit by hand — your changes will be overwritten.",
    " *",
    " * The runtime merges this seed with ~/.argentos/provider-registry.json.",
    " * Keeping this module present avoids startup noise when the API server",
    " * expects a local provider catalog artifact.",
    " */",
    "",
  ].join("\n");

  const registryJson = JSON.stringify(registry, null, 2);
  const body = `module.exports = {\n  PROVIDER_REGISTRY_SEED_VERSION: ${SEED_VERSION},\n  DEFAULT_PROVIDER_REGISTRY: ${registryJson},\n};\n`;

  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  fs.writeFileSync(outputPath, banner + body, "utf-8");

  console.log(
    `[export-provider-catalog] Wrote ${providerCount} providers (seed v${SEED_VERSION}) → ${path.relative(projectRoot, outputPath)}`,
  );
}

exportProviderCatalog();
