from __future__ import annotations

TOOL_NAME = "aos-woocommerce"
BACKEND_NAME = "woocommerce-rest-api"
MANIFEST_VERSION = "1.0.0"
API_VERSION = "wc/v3"
DEFAULT_TIMEOUT_SECONDS = 20
ENV_CONSUMER_KEY = "WOO_CONSUMER_KEY"
ENV_CONSUMER_SECRET = "WOO_CONSUMER_SECRET"
ENV_STORE_URL = "WOO_STORE_URL"
ENV_ORDER_ID = "WOO_ORDER_ID"
ENV_PRODUCT_ID = "WOO_PRODUCT_ID"
ENV_CUSTOMER_ID = "WOO_CUSTOMER_ID"
ENV_ORDER_STATUS = "WOO_ORDER_STATUS"
ENV_PRODUCT_STATUS = "WOO_PRODUCT_STATUS"
ENV_SKU = "WOO_SKU"
