/**
 * Vision Fallback Middleware
 *
 * When the active model doesn't support image input, this module automatically
 * describes any inline image content blocks in the conversation history using
 * the MiniMax VLM endpoint, then replaces them with text descriptions.
 *
 * This allows a single MiniMax API key to power text + vision on models that
 * don't natively support multimodal input.
 */

import { minimaxUnderstandImage, resolveMinimaxApiKeyAsync } from "../../minimax-vlm.js";
import { log } from "../logger.js";

type ContentBlock = {
  type: string;
  text?: string;
  data?: string;
  mimeType?: string;
};

type MessageLike = {
  role?: string;
  content?: unknown;
  [key: string]: unknown;
};

const DEFAULT_MAX_DESCRIBED_IMAGES = 2;
const DEFAULT_TOTAL_BUDGET_MS = 12_000;
const DEFAULT_PER_IMAGE_TIMEOUT_MS = 4_000;
const SKIP_NOTE = "[Image attached — description skipped to keep response fast]";

function hasContentArray(msg: unknown): msg is MessageLike & { content: ContentBlock[] } {
  if (!msg || typeof msg !== "object") return false;
  const m = msg as Record<string, unknown>;
  return Array.isArray(m.content);
}

function resolvePositiveInt(name: string, fallback: number, min: number, max: number): number {
  const parsed = Number.parseInt(process.env[name] ?? "", 10);
  if (!Number.isFinite(parsed) || parsed <= 0) return fallback;
  return Math.min(Math.max(parsed, min), max);
}

function countInlineImages(messages: unknown[]): number {
  let count = 0;
  for (const msg of messages) {
    if (!hasContentArray(msg)) continue;
    for (const block of msg.content) {
      if (block.type === "image" && block.data) {
        count += 1;
      }
    }
  }
  return count;
}

/**
 * Describes a single inline image block using the MiniMax VLM endpoint.
 */
async function describeImageBlock(
  block: ContentBlock,
  apiKey: string,
  modelBaseUrl?: string,
  timeoutMs?: number,
): Promise<string> {
  const mime = block.mimeType ?? "image/jpeg";
  const imageDataUrl = `data:${mime};base64,${block.data}`;
  try {
    return await minimaxUnderstandImage({
      apiKey,
      prompt:
        "Describe this image in detail. Include all visible text, objects, people, colors, layout, and any other relevant information.",
      imageDataUrl,
      modelBaseUrl,
      timeoutMs,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return `[Image could not be described: ${msg}]`;
  }
}

/**
 * Scans messages for inline image content blocks. Returns true if any exist.
 */
export function messagesHaveInlineImages(messages: unknown[]): boolean {
  for (const msg of messages) {
    if (!hasContentArray(msg)) continue;
    for (const block of msg.content) {
      if (block.type === "image" && block.data) return true;
    }
  }
  return false;
}

/**
 * Replaces all inline image content blocks in conversation messages with
 * text descriptions generated by the MiniMax VLM endpoint.
 *
 * Only runs when:
 * - The active model doesn't support vision (modelHasVision === false)
 * - There are inline image blocks in the messages
 * - A MiniMax API key is available (MINIMAX_CODE_PLAN_KEY or MINIMAX_API_KEY)
 *
 * @returns The modified messages array (same reference if no changes needed)
 */
export async function applyVisionFallbackToMessages<T>(
  messages: T[],
  opts: {
    modelHasVision: boolean;
    minimaxBaseUrl?: string;
  },
): Promise<T[]> {
  if (opts.modelHasVision) return messages;
  if (!messagesHaveInlineImages(messages as unknown[])) return messages;

  const totalInlineImages = countInlineImages(messages as unknown[]);
  const maxDescribedImages = resolvePositiveInt(
    "ARGENT_VISION_FALLBACK_MAX_IMAGES",
    DEFAULT_MAX_DESCRIBED_IMAGES,
    1,
    20,
  );
  const totalBudgetMs = resolvePositiveInt(
    "ARGENT_VISION_FALLBACK_BUDGET_MS",
    DEFAULT_TOTAL_BUDGET_MS,
    1_000,
    120_000,
  );
  const perImageTimeoutMs = resolvePositiveInt(
    "ARGENT_VISION_FALLBACK_TIMEOUT_MS",
    DEFAULT_PER_IMAGE_TIMEOUT_MS,
    500,
    60_000,
  );

  const apiKey = await resolveMinimaxApiKeyAsync();

  if (!apiKey) {
    // No MiniMax key — strip images silently to avoid API errors
    log.warn(
      `[vision-fallback] no MiniMax key available; stripping ${totalInlineImages} inline image(s) from history`,
    );
    return stripInlineImages(messages);
  }

  const startedAt = Date.now();
  let describedCount = 0;
  let skippedCount = 0;
  const result: T[] = [];
  for (const msg of messages) {
    if (!hasContentArray(msg)) {
      result.push(msg);
      continue;
    }

    const blocks = msg.content;
    const hasImages = blocks.some((b) => b.type === "image" && b.data);
    if (!hasImages) {
      result.push(msg);
      continue;
    }

    // Replace image blocks with text descriptions
    const newBlocks: ContentBlock[] = [];
    for (const block of blocks) {
      if (block.type === "image" && block.data) {
        const elapsedMs = Date.now() - startedAt;
        if (describedCount >= maxDescribedImages || elapsedMs >= totalBudgetMs) {
          skippedCount += 1;
          newBlocks.push({ type: "text", text: SKIP_NOTE });
          continue;
        }
        const description = await describeImageBlock(
          block,
          apiKey,
          opts.minimaxBaseUrl,
          perImageTimeoutMs,
        );
        describedCount += 1;
        newBlocks.push({ type: "text", text: `[Image: ${description}]` });
      } else {
        newBlocks.push(block);
      }
    }

    result.push({ ...msg, content: newBlocks } as T);
  }

  const durationMs = Date.now() - startedAt;
  if (skippedCount > 0 || durationMs > totalBudgetMs) {
    log.warn(
      `[vision-fallback] processed inline images with guardrails total=${totalInlineImages} described=${describedCount} skipped=${skippedCount} durationMs=${durationMs} budgetMs=${totalBudgetMs}`,
    );
  } else {
    log.debug(
      `[vision-fallback] processed inline images total=${totalInlineImages} described=${describedCount} durationMs=${durationMs}`,
    );
  }

  return result;
}

/**
 * Strips image blocks entirely (used when no vision API key is available).
 */
function stripInlineImages<T>(messages: T[]): T[] {
  return messages.map((msg) => {
    if (!hasContentArray(msg)) return msg;
    const blocks = msg.content;
    const hasImages = blocks.some((b) => b.type === "image");
    if (!hasImages) return msg;

    const newBlocks = blocks.map((b) =>
      b.type === "image" ? { type: "text", text: "[Image attached — vision not available]" } : b,
    );
    return { ...msg, content: newBlocks } as T;
  });
}
