/**
 * ElevenLabs v3 Audio Tags Library
 *
 * Comprehensive, categorized library of audio tags supported by the
 * ElevenLabs Eleven v3 TTS model. Tags are placed in square brackets
 * within text to direct vocal delivery, emotions, sound effects, and more.
 *
 * Usage: "[excited] Oh wow, this is amazing! [laughs]"
 *
 * Sources: ElevenLabs official docs, audio-generation-plugin.com tag library
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface AudioTag {
  tag: string;
  category: string;
  description?: string;
}

// ---------------------------------------------------------------------------
// Category definitions
// ---------------------------------------------------------------------------

export const V3_TAG_CATEGORIES = [
  "Emotions",
  "Delivery & Direction",
  "Human Reactions",
  "Sound Effects",
  "Accents & Dialects",
  "Pacing & Flow",
  "Comedy & Performance",
  "Narrative & Storytelling",
  "Character Archetypes",
  "Body States",
  "Environment & Atmosphere",
  "Dialogue",
  "Genre & Tone",
  "Effects & Modulation",
  "Time & Mood Context",
] as const;

export type V3TagCategory = (typeof V3_TAG_CATEGORIES)[number];

// ---------------------------------------------------------------------------
// Tag data by category
// ---------------------------------------------------------------------------

const EMOTIONS: string[] = [
  // Core emotions
  "happy",
  "sad",
  "angry",
  "excited",
  "nervous",
  "calm",
  "anxious",
  "frustrated",
  "sorrowful",
  "confused",
  "surprised",
  "disgusted",
  "fearful",
  "joyful",
  "content",
  "bored",
  "amused",
  "annoyed",
  // Intensity variants
  "furious",
  "enraged",
  "irritated",
  "livid",
  "seething",
  "ecstatic",
  "elated",
  "thrilled",
  "overjoyed",
  "giddy",
  "devastated",
  "heartbroken",
  "grief-stricken",
  "melancholic",
  "gloomy",
  "terrified",
  "horrified",
  "petrified",
  "panicked",
  "dread",
  // Nuanced emotions
  "wistful",
  "nostalgic",
  "longing",
  "yearning",
  "homesick",
  "bitter",
  "resentful",
  "envious",
  "jealous",
  "spiteful",
  "grateful",
  "appreciative",
  "thankful",
  "humbled",
  "blessed",
  "proud",
  "triumphant",
  "accomplished",
  "smug",
  "self-satisfied",
  "guilty",
  "ashamed",
  "remorseful",
  "regretful",
  "embarrassed",
  "hopeful",
  "optimistic",
  "encouraged",
  "inspired",
  "motivated",
  "hopeless",
  "despairing",
  "defeated",
  "resigned",
  "helpless",
  "sympathetic",
  "empathetic",
  "compassionate",
  "pitying",
  "concerned",
  "suspicious",
  "distrustful",
  "wary",
  "skeptical",
  "paranoid",
  "indifferent",
  "apathetic",
  "detached",
  "numb",
  "disengaged",
  "amazed",
  "awestruck",
  "wonder",
  "fascinated",
  "captivated",
  "uncomfortable",
  "uneasy",
  "awkward",
  "self-conscious",
  "flustered",
  "determined",
  "resolute",
  "steadfast",
  "unwavering",
  "tenacious",
  "playful",
  "mischievous",
  "cheeky",
  "impish",
  "teasing",
  "loving",
  "adoring",
  "affectionate",
  "tender",
  "warm",
  "lonely",
  "isolated",
  "abandoned",
  "forlorn",
  "desolate",
  "curious",
  "intrigued",
  "inquisitive",
  "puzzled",
  "perplexed",
  "relieved",
  "reassured",
  "comforted",
  "at ease",
  "unburdened",
  "contemptuous",
  "disdainful",
  "scornful",
  "dismissive",
  "condescending",
  "enthusiastic",
  "eager",
  "keen",
  "passionate",
  "zealous",
  "exasperated",
  "fed up",
  "at wits end",
  "impatient",
  "aggravated",
  "blissful",
  "euphoric",
  "rapturous",
  "serene",
  "tranquil",
  "conflicted",
  "torn",
  "ambivalent",
  "uncertain",
  "hesitant",
  "defiant",
  "rebellious",
  "stubborn",
  "obstinate",
  "uncooperative",
  "vulnerable",
  "exposed",
  "fragile",
  "insecure",
  "defenseless",
  "confident",
  "assured",
  "bold",
  "fearless",
  "courageous",
  "depressed",
  "despondent",
  "disheartened",
  "dispirited",
  "downcast",
  "manic",
  "frenzied",
  "hysterical",
  "unhinged",
  "wild",
  "stoic",
  "impassive",
  "unflappable",
  "composed",
  "collected",
  "wicked",
  "malicious",
  "sinister",
  "menacing",
  "threatening",
  "flirtatious",
  "coy",
  "seductive",
  "alluring",
  "sultry",
  "contemplative",
  "thoughtful",
  "pensive",
  "reflective",
  "meditative",
  "restless",
  "agitated",
  "fidgety",
  "antsy",
  "on edge",
  "weary",
  "exhausted",
  "drained",
  "fatigued",
  "spent",
  "energetic",
  "vibrant",
  "lively",
  "spirited",
  "dynamic",
  "anticipatory",
  "expectant",
  "suspenseful",
  // Adverbial forms
  "happily",
  "sadly",
  "angrily",
  "excitedly",
  "nervously",
  "calmly",
  "anxiously",
  "cheerfully",
  "mischievously",
  "proudly",
  "warmly",
  "gently",
  "coldly",
  "bitterly",
  "lovingly",
  "desperately",
  "cautiously",
  "timidly",
  "boldly",
  "fiercely",
];

const DELIVERY_DIRECTION: string[] = [
  // Volume & energy
  "whispers",
  "whispering",
  "soft whisper",
  "hushed",
  "sotto voce",
  "shouts",
  "shouting",
  "yells",
  "yelling",
  "screams",
  "screaming",
  "murmurs",
  "murmuring",
  "muttering",
  "under breath",
  "booming",
  "thundering",
  "bellowing",
  // Tone
  "sarcastic",
  "sarcastically",
  "dry humor",
  "deadpan",
  "ironic",
  "sincere",
  "genuine",
  "heartfelt",
  "earnest",
  "commanding",
  "authoritative",
  "firm",
  "stern",
  "strict",
  "caring",
  "nurturing",
  "motherly",
  "fatherly",
  "parental",
  "sympathetic",
  "comforting",
  "soothing",
  "reassuring",
  "threatening",
  "menacing",
  "ominous",
  "foreboding",
  "mocking",
  "taunting",
  "jeering",
  "sneering",
  "derisive",
  "pleading",
  "begging",
  "imploring",
  "beseeching",
  "matter-of-fact",
  "clinical",
  "businesslike",
  "professional",
  "casual",
  "relaxed",
  "laid-back",
  "easygoing",
  "formal",
  "stiff",
  "proper",
  "prim",
  "conspiratorial",
  "secretive",
  "hushed tone",
  "accusatory",
  "confrontational",
  "aggressive",
  "defensive",
  "guarded",
  "evasive",
  "flippant",
  "dismissive",
  "nonchalant",
  "reverent",
  "worshipful",
  "devotional",
  "patronizing",
  "condescending",
  "talking down",
  "encouraging",
  "supportive",
  "uplifting",
  "cautionary",
  "warning tone",
  "ominous tone",
  "instructional",
  "educational",
  "teaching",
  "confessional",
  "intimate",
  "vulnerable tone",
  "through gritted teeth",
  "clenched jaw",
  "clipped tone",
  "terse",
  "curt",
  "abrupt",
  "sing-song",
  "melodic",
  "lilting",
  "musical",
  "monotone",
  "flat",
  "expressionless",
  "robotic",
  "breathy",
  "airy",
  "wispy",
  "gravelly",
  "raspy",
  "hoarse",
  "scratchy",
  "nasal",
  "whiny",
  "nasally",
  "boisterous",
  "rowdy",
  "raucous",
  "dignified",
  "regal",
  "noble",
  "majestic",
  "creepy",
  "unsettling",
  "eerie",
];

const HUMAN_REACTIONS: string[] = [
  // Laughter
  "laughs",
  "laughing",
  "laughs harder",
  "starts laughing",
  "chuckles",
  "giggles",
  "giggling",
  "snickers",
  "snickering",
  "cackles",
  "belly laugh",
  "nervous laugh",
  "forced laugh",
  "hysterical laughter",
  "awkward laugh",
  "maniacal laugh",
  "evil laugh",
  "wheeze laugh",
  "laugh fit",
  "giggle fit",
  "laughing uncontrollably",
  // Breathing
  "sighs",
  "deep sigh",
  "heavy sigh",
  "resigned sigh",
  "contented sigh",
  "exhales",
  "exhales sharply",
  "inhales deeply",
  "breathing heavily",
  "gasps",
  "sharp gasp",
  "startled gasp",
  "shocked gasp",
  "heavy breathing",
  "panting",
  "short of breath",
  "catches breath",
  "holds breath",
  "breathes",
  // Crying
  "crying",
  "sobbing",
  "weeping",
  "whimpering",
  "sniffling",
  "tears up",
  "chokes up",
  "voice breaking",
  "voice cracks",
  "wailing",
  "bawling",
  // Throat & mouth
  "clears throat",
  "coughs",
  "coughing",
  "cough",
  "gulps",
  "swallows",
  "dry swallow",
  "hiccups",
  "hiccuping",
  "burps",
  "yawns",
  "yawning",
  "groans",
  "moans",
  "grunts",
  "scoffs",
  "scoffing",
  "snorts",
  "snorting",
  "hums",
  "humming",
  "whistles",
  "whistling",
  "sings",
  "singing",
  // Vocal tics
  "stammers",
  "stutters",
  "stumbles over words",
  "voice trembling",
  "voice shaking",
  "quivering voice",
  "wheezing",
  "wheeze",
  "tuts",
  "tsk",
  "clicks tongue",
  "mumbles",
  "slurs",
  "shushes",
  "shushing",
  "growls",
  "growling",
  "snarls",
  "hisses",
  "hissing",
  "squeals",
  "squeaking",
  "yelps",
  "woo",
  "woah",
  "ohh",
  "ahh",
  "hmm",
  "ugh",
  "eep",
  "phew",
  "whew",
  "oh no",
  "oh my",
  // Physical
  "sneezes",
  "sneezing",
  "sniffles",
  "choking",
  "gagging",
  "retching",
  "fart",
  "belch",
];

const SOUND_EFFECTS: string[] = [
  // Audience
  "applause",
  "cheers",
  "cheering",
  "boo",
  "booing",
  "clapping",
  "slow clap",
  "standing ovation",
  "crowd roar",
  "audience laughter",
  "audience gasp",
  "crowd murmur",
  "crowd chanting",
  "whistling crowd",
  // Impact
  "gunshot",
  "gunfire",
  "explosion",
  "boom",
  "bang",
  "crash",
  "thud",
  "thump",
  "slam",
  "smash",
  "shatter",
  "crack",
  "snap",
  "pop",
  "crunch",
  "crumble",
  "ricochet",
  "impact",
  "collision",
  // Nature
  "thunder",
  "lightning",
  "rain",
  "rain heavy",
  "rain light",
  "drizzle",
  "hail",
  "thunderstorm",
  "wind",
  "wind howling",
  "wind gusting",
  "breeze",
  "leaves rustling",
  "branches snapping",
  "tree falling",
  "waves",
  "ocean waves",
  "waterfall",
  "stream",
  "river flowing",
  "bird chirping",
  "birds singing",
  "owl hoot",
  "crow caw",
  "wolf howl",
  "dog bark",
  "cat meow",
  "horse neigh",
  "rooster crow",
  "frog ribbit",
  "snake hiss",
  "bee buzzing",
  "crickets",
  "buzzing",
  "cicadas",
  "earthquake",
  "avalanche",
  "rockslide",
  // Mechanical
  "door slam",
  "door creak",
  "door knock",
  "knocking",
  "banging on door",
  "glass breaking",
  "glass shattering",
  "window crack",
  "car horn",
  "car engine",
  "car crash",
  "car passing",
  "siren",
  "alarm",
  "bell",
  "phone ringing",
  "doorbell",
  "clock ticking",
  "ticking",
  "clock chime",
  "engine rumble",
  "motor",
  "machinery",
  "gears grinding",
  "train whistle",
  "train rumbling",
  "plane overhead",
  "helicopter",
  "boat horn",
  "ship horn",
  "typewriter",
  "keyboard typing",
  "mouse click",
  "cash register",
  "coin drop",
  "checkout beep",
  "hammer",
  "drilling",
  "sawing",
  "welding",
  "lock clicking",
  "handcuffs",
  "gate creaking",
  "elevator ding",
  "escalator hum",
  // Electronic
  "beep",
  "buzz",
  "static",
  "radio static",
  "dial tone",
  "notification",
  "ringtone",
  "power up",
  "power down",
  "charging",
  "error sound",
  "success sound",
  "alert",
  "sonar ping",
  "radar blip",
  // Weapons & combat
  "sword clash",
  "sword draw",
  "arrow whoosh",
  "shield block",
  "armor clank",
  "whip crack",
  "cannon fire",
  "musket shot",
  "laser blast",
  "bow string",
  "axe swing",
  "mace impact",
  // Music
  "drum roll",
  "fanfare",
  "trumpet",
  "guitar strum",
  "piano chord",
  "orchestra hit",
  "cymbal crash",
  "violin screech",
  "bass drop",
  "drum beat",
  "harp glissando",
  "flute trill",
  "bagpipes",
  // Ambient
  "footsteps",
  "running footsteps",
  "shuffling",
  "paper rustling",
  "page turning",
  "paper tearing",
  "fire crackling",
  "campfire",
  "bonfire roar",
  "bubbling",
  "dripping",
  "splashing",
  "pouring",
  "chains rattling",
  "keys jingling",
  "coins clinking",
  "zipper",
  "velcro",
  "fabric tearing",
  "heartbeat",
  "heart pounding",
  "pulse",
  "record scratch",
  "vinyl pop",
  "cork pop",
  "bottle open",
  "can open",
  "ice cubes",
  "liquid pouring",
  "sizzling",
  "chopping",
  "stirring",
  "blender",
];

const ACCENTS_DIALECTS: string[] = [
  // English variants
  "American accent",
  "British accent",
  "Australian accent",
  "Canadian accent",
  "New Zealand accent",
  "South African accent",
  "Irish accent",
  "Scottish accent",
  "Welsh accent",
  // US regional
  "Southern US accent",
  "Southern drawl",
  "New York accent",
  "Boston accent",
  "Midwest accent",
  "California accent",
  "Texas accent",
  "Brooklyn accent",
  "Appalachian accent",
  // UK regional
  "Cockney accent",
  "Received Pronunciation",
  "Yorkshire accent",
  "Manchester accent",
  "Birmingham accent",
  "Liverpool accent",
  "Geordie accent",
  "West Country accent",
  "Estuary English",
  "posh British accent",
  // European
  "French accent",
  "German accent",
  "Spanish accent",
  "Italian accent",
  "Russian accent",
  "Portuguese accent",
  "Dutch accent",
  "Swedish accent",
  "Norwegian accent",
  "Danish accent",
  "Finnish accent",
  "Polish accent",
  "Greek accent",
  "Romanian accent",
  "Czech accent",
  "Hungarian accent",
  "Turkish accent",
  // Asian
  "Indian English",
  "Indian accent",
  "Japanese accent",
  "Chinese accent",
  "Korean accent",
  "Thai accent",
  "Vietnamese accent",
  "Filipino accent",
  // Other
  "Middle Eastern accent",
  "Arabic accent",
  "Caribbean accent",
  "Jamaican accent",
  "Nigerian accent",
  "Kenyan accent",
  "Brazilian accent",
  "Mexican accent",
  "strong accent",
  "slight accent",
  "thick accent",
  "heavy accent",
  // Character/fantasy accents
  "pirate voice",
  "pirate accent",
  "elvish",
  "dwarven",
  "orcish",
  "Transylvanian accent",
  "Dracula voice",
];

const PACING_FLOW: string[] = [
  // Pauses
  "pause",
  "pauses",
  "short pause",
  "long pause",
  "dramatic pause",
  "beat",
  "continues after a beat",
  "pregnant pause",
  "awkward pause",
  "silence",
  // Speed
  "rushed",
  "rapid",
  "rapid-fire",
  "fast-paced",
  "hurried",
  "slow",
  "slowly",
  "deliberate",
  "measured",
  "unhurried",
  "slows down",
  "speeds up",
  "accelerating",
  "decelerating",
  // Rhythm
  "drawn out",
  "elongated",
  "lingering",
  "dragging",
  "staccato",
  "clipped",
  "punchy",
  "sharp",
  "flowing",
  "smooth",
  "rhythmic",
  "rhythmically",
  "syncopated",
  "halting",
  "stop and start",
  // Hesitation
  "hesitates",
  "hesitantly",
  "falters",
  "trails off",
  "interrupts",
  "interrupting",
  "cuts off",
  "cuts in",
  "stammering",
  "fumbling for words",
  "repeats",
  "corrects self",
  "self-interrupt",
  "overlapping",
  "overlapping speech",
  "talks over",
  // Emphasis
  "emphasizes",
  "stresses",
  "underscores",
  "pitch rises",
  "pitch drops",
  "voice rises",
  "crescendo",
  "decrescendo",
  "building",
  "trailing off",
  "fading",
  "dying away",
];

const COMEDY_PERFORMANCE: string[] = [
  // Comedy styles
  "deadpan delivery",
  "dry wit",
  "sarcastic quip",
  "over the top",
  "exaggerated",
  "hamming it up",
  "tongue in cheek",
  "wry",
  "sardonic",
  "absurd",
  "absurdist",
  "surreal humor",
  "self-deprecating",
  "self-mocking",
  "punchline delivery",
  "setup",
  "callback",
  "comic timing",
  "comic relief",
  "double take",
  "spit take",
  "campy",
  "campy tone",
  "camp",
  "kitschy",
  "slapstick voice",
  "goofy",
  "dopey",
  "zany",
  "witty",
  "clever",
  "quippy",
  "biting sarcasm",
  "savage",
  "brutal honesty",
  "parody",
  "mockery",
  "impression",
  "friendly tease",
  "ribbing",
  "playful jab",
  "inside joke",
  "running gag",
  "cringe",
  "awkward humor",
  "uncomfortable comedy",
  "observational",
  "relatable humor",
  // Performance
  "dramatic",
  "dramatic tone",
  "theatrical",
  "over-dramatic",
  "melodramatic",
  "operatic",
  "pompous",
  "grandiose",
  "bombastic",
  "understated",
  "subtle",
  "low-key",
  "unhinged energy",
  "chaotic",
  "frantic",
  "gleeful",
  "devilish",
  "wicked grin",
  // Impressions & characters
  "villain voice",
  "evil scientist voice",
  "hero voice",
  "announcer voice",
  "game show host",
  "news anchor",
  "sports announcer",
  "radio DJ",
  "valley girl",
  "surfer dude",
  "nerd voice",
  "tough guy",
  "mob boss",
  "cowboy voice",
  "goblin noises",
  "monster voice",
  "childlike tone",
  "baby voice",
  "old person voice",
  "robot voice",
  "AI voice",
  "computer voice",
  "alien voice",
  "ghost voice",
  "demon voice",
  "narrator voice",
  "storyteller voice",
  "drill sergeant",
  "cheerleader",
  "auctioneer",
  "preacher voice",
  "newscaster voice",
  "weatherperson",
];

const NARRATIVE_STORYTELLING: string[] = [
  // Narration styles
  "narrator",
  "narrating",
  "voice-over",
  "voice over style",
  "omniscient narrator",
  "first-person narrative",
  "third-person narrative",
  "unreliable narrator",
  "stream of consciousness",
  "documentary style",
  "mockumentary tone",
  "audiobook style",
  "storybook style",
  "fairytale style",
  "bedtime story",
  "campfire storytelling",
  "epic saga tone",
  "mythic tone",
  "legendary tone",
  "fable style",
  "parable tone",
  "kids story tone",
  "adult story tone",
  "oral history style",
  "found footage style",
  // Dramatic devices
  "dramatic reveal",
  "suspense build-up",
  "cliffhanger",
  "flashback tone",
  "flashforward tone",
  "foreshadowing",
  "plot twist",
  "revelation",
  "epiphany",
  "inner monologue",
  "aside",
  "breaking fourth wall",
  "soliloquy",
  "monologue",
  "dialogue",
  "narrator aside",
  "narrator interrupts",
  "slow reveal",
  "fast-paced narration",
  "pauses for effect",
  "crescendo tone",
  "anticlimactic reveal",
  // Reading styles
  "prose reading",
  "poetic reading",
  "poetry",
  "poetic imagery",
  "vivid description",
  "sensory detail",
  "letter reading",
  "journal entry",
  "diary entry",
  "news report",
  "breaking news",
  "headline",
  "news anchor tone",
  "reporter style",
  "weather reporter tone",
  "sports announcer",
  "play-by-play style",
  "lecture",
  "sermon",
  "speech",
  "prayer",
  "toast",
  "eulogy",
  "vow",
  "podcast host",
  "vlog style",
  "casual chat",
  "studio announcer",
  "interview style",
  // Narrative tone
  "narrative flourish",
  "storytelling tone",
  "cinematic tone",
  "epic build-up",
  "anticlimactic",
  "bittersweet",
  "foreboding",
  "ominous narration",
  "uplifting narration",
  "inspiring",
  "melancholic narration",
  "tragic narration",
  "humorous narration",
  "lighthearted",
  "tense narration",
  "edge of seat",
  "calming narration",
  "soothing narration",
  "mystery narration",
  "noir narration",
  "detective story tone",
  "horror narration",
  "ghost story tone",
  "urban legend tone",
  "romantic narration",
  "love story",
  "adventure narration",
  "action sequence",
  "comedy narration",
  "satirical narration",
  "sarcastic narration",
  "deadpan narration",
  "whimsical style",
  "quirky tone",
  "absurdist narration",
  "minimalist narration",
  "maximalist narration",
  "understated tone",
  "over-the-top narration",
  "informative",
  "analytical",
  "scientific",
  "educational tone",
  "instructional",
  "tutorial",
  "explainer",
  "motivational",
  "motivational tone",
  "coach voice",
  "mentor voice",
  "confessional",
  "confessional tone",
  "testimonial",
  "historical recount",
  "memoir",
  "memoir tone",
  "wonder-filled narration",
  "childlike narration",
  "dead serious narration",
  "mock heroic tone",
  "tragicomedy tone",
  "moralizing tone",
  "hopeful narration",
  "doubtful narration",
  "skeptical narration",
  "refrain voice",
  "callback narration",
];

const CHARACTER_ARCHETYPES: string[] = [
  // Classic
  "hero",
  "villain",
  "sidekick",
  "mentor",
  "trickster",
  "wise old man",
  "wise woman",
  "sage",
  "oracle",
  "damsel",
  "knight",
  "king",
  "queen",
  "prince",
  "princess",
  // Fantasy
  "wizard",
  "witch",
  "sorcerer",
  "enchantress",
  "dragon",
  "giant",
  "fairy",
  "elf",
  "dwarf",
  "goblin",
  "orc",
  "troll",
  "imp",
  // Modern
  "detective",
  "spy",
  "secret agent",
  "mad scientist",
  "professor",
  "doctor",
  "soldier",
  "captain",
  "general",
  "pirate",
  "cowboy",
  "outlaw",
  "sheriff",
  "vampire",
  "werewolf",
  "zombie",
  "ghost",
  "spirit",
  "phantom",
  "robot",
  "android",
  "cyborg",
  "AI",
  "alien",
  "space captain",
  "superhero",
  "vigilante",
  "antihero",
  // Social
  "bully",
  "rebel",
  "loner",
  "outsider",
  "class clown",
  "jock",
  "nerd",
  "geek",
  "socialite",
  "diva",
  "snob",
  "bartender",
  "taxi driver",
  "librarian",
  "butler",
  "maid",
  "servant",
];

const BODY_STATES: string[] = [
  // Temperature & shaking
  "shivering",
  "trembling",
  "shaking",
  "quaking",
  "freezing",
  "cold",
  "chilled",
  "cold shiver",
  "overheated",
  "burning up",
  "feverish",
  "heat wave",
  "teeth chattering",
  // Perspiration & skin
  "sweating",
  "sweaty",
  "clammy",
  "sweat dripping",
  "clammy skin",
  "goosebumps",
  "hair standing",
  "cold skin",
  "blushing",
  "flushed",
  "pale",
  "sunburned",
  "dry skin",
  "tingling",
  "numb",
  // Balance & movement
  "dizzy",
  "lightheaded",
  "faint",
  "woozy",
  "staggering",
  "limping",
  "stumbling",
  "swaying",
  "stretching",
  "cracking joints",
  "cracking knuckles",
  "hunched",
  "slouching",
  "standing tall",
  "sit slowly",
  "stand slowly",
  "walk softly",
  "run softly",
  "crawl",
  "limp slowly",
  // Hunger & thirst
  "hungry",
  "thirsty",
  "starving",
  "stomach gurgling",
  "hungry grumbling",
  "stomach rumble",
  "full belly",
  // Illness
  "nauseous",
  "queasy",
  "sick",
  "coughing lightly",
  "wheezing softly",
  "sore throat",
  "tight chest",
  "headache",
  "throbbing",
  "migraine",
  // Pain
  "in pain",
  "aching",
  "sore",
  "sharp pain",
  "stiff neck",
  "sore muscles",
  "cramps",
  "muscle twitch",
  "back pain",
  "stiff joints",
  "knee knock",
  "shin pain",
  // Energy
  "tired",
  "tiredly",
  "sleepy",
  "drowsy",
  "groggy",
  "exhausted",
  "drained",
  "fatigued",
  "spent",
  "energized",
  "wired",
  "buzzing with energy",
  "restless",
  "can't sit still",
  // Intoxication
  "drunk",
  "tipsy",
  "slurring",
  "intoxicated",
  "hungover",
  "disoriented",
  // Breathing
  "out of breath",
  "winded",
  "panting",
  "breathing heavily",
  "short of breath",
  // Tension
  "tense",
  "stiff",
  "rigid",
  "relaxed",
  "loose",
  "limp",
  "jittery",
  "fidgety",
  "twitchy",
  "adrenaline rush",
  "heart racing",
  // Face & expression
  "jaw clenching",
  "teeth grinding",
  "lip quivering",
  "lip biting",
  "chin trembling",
  "eye twitching",
  "blinking rapidly",
  "eye roll",
  "blank stare",
  "focused glance",
  "mouth dry",
  "mouth watery",
  "swallow saliva",
  // Waking/sleeping
  "wake up stretch",
  "yawn stretch",
  "sleep rustle",
];

const ENVIRONMENT_ATMOSPHERE: string[] = [
  // Nature - forests
  "forest morning",
  "forest midday",
  "forest dusk",
  "forest night",
  "jungle ambient",
  "rainforest ambient",
  "bamboo grove",
  "pine forest",
  "tropical forest",
  // Nature - other biomes
  "desert daytime",
  "desert night",
  "desert wind",
  "mountain peak",
  "mountain pass",
  "mountain ambient",
  "beach waves",
  "beach breeze",
  "beach party",
  "cave ambient",
  "cave dripping",
  "deep cavern",
  "underwater",
  "deep sea",
  "coral reef",
  "swamp ambient",
  "marshland",
  "bayou",
  "tundra",
  "arctic wind",
  "glacier",
  "savanna",
  "grassland",
  "prairie",
  "volcano rumble",
  "hot springs",
  // Nature - weather
  "rainy atmosphere",
  "stormy atmosphere",
  "snowy atmosphere",
  "windy atmosphere",
  "foggy atmosphere",
  "misty atmosphere",
  "blizzard",
  "dust storm",
  "tornado siren",
  "rainbow after storm",
  "clear sky",
  // Time of day
  "sunrise mood",
  "sunset mood",
  "golden hour",
  "twilight",
  "midnight mood",
  "dawn breaking",
  "dusk settling",
  "starlit night",
  "moonlit night",
  // Urban
  "city street",
  "city traffic",
  "city ambient",
  "city siren",
  "city crowd",
  "city subway",
  "city nightlife",
  "subway rumble",
  "train station",
  "train arrival",
  "airport ambient",
  "airport announcement",
  "cafe ambient",
  "cafe barista",
  "cafe conversation",
  "restaurant bustle",
  "restaurant kitchen",
  "restaurant ambient",
  "bar ambient",
  "pub noise",
  "nightclub",
  "office ambient",
  "office typing",
  "office chatter",
  "classroom ambient",
  "school bell",
  "children chatter",
  "library ambient",
  "quiet whisper",
  "hospital ambient",
  "hospital monitors",
  "hospital intercom",
  "church ambient",
  "church bells",
  "choir",
  "stadium crowd",
  "stadium cheer",
  "stadium announcer",
  "concert ambient",
  "festival crowd",
  "construction site",
  "factory ambient",
  "factory machinery",
  "market ambient",
  "market vendor",
  "market crowd",
  "mall ambient",
  "shopping center",
  "parking garage",
  "gas station",
  "harbor",
  "dockyard",
  "marina",
  // Interior
  "cozy room",
  "empty room",
  "echoing hall",
  "grand ballroom",
  "basement",
  "attic",
  "cellar",
  "wine cellar",
  "haunted house",
  "abandoned building",
  "derelict",
  "throne room",
  "dungeon",
  "castle hall",
  "spaceship interior",
  "cockpit",
  "space station",
  "laboratory",
  "control room",
  "server room",
  "recording studio",
  "sound stage",
  "courtroom",
  "prison cell",
  "interrogation room",
  "bathroom echo",
  "shower running",
  "elevator",
  "stairwell echo",
  "tent",
  "campsite",
  "cabin",
  "greenhouse",
  "garden",
  "zen garden",
  // Mood
  "peaceful",
  "chaotic",
  "eerie atmosphere",
  "tense atmosphere",
  "romantic atmosphere",
  "mysterious atmosphere",
  "magical atmosphere",
  "apocalyptic",
  "dystopian atmosphere",
  "nostalgic atmosphere",
  "dreamlike",
  "nightmarish",
  "surreal atmosphere",
  "meditative atmosphere",
  "sacred space",
  "industrial",
  "desolate",
  "vibrant",
  "claustrophobic",
  "vast open",
  "infinite",
];

const DIALOGUE_TAGS: string[] = [
  // Turn-taking
  "interrupts",
  "interrupting",
  "cuts in",
  "talks over",
  "overlapping speech",
  "back and forth",
  "rapid exchange",
  "slow exchange",
  "takes turn",
  // Response dynamics
  "responds quickly",
  "responds slowly",
  "asks politely",
  "asks bluntly",
  "demands",
  "insists",
  "urges",
  "suggests",
  "proposes",
  "agrees reluctantly",
  "agrees eagerly",
  "refuses",
  "declines",
  "rejects",
  "negotiates",
  "bargains",
  "compromises",
  "apologizes mid-sentence",
  "stammered apology",
  // Corrections
  "corrects self",
  "rephrases",
  "clarifies",
  "backtracks",
  "second-guesses",
  "doubles down",
  "self-interrupt",
  "interrupted thought",
  "paraphrases",
  "summarizes",
  "reframes",
  // Dialogue dynamics
  "pitch rises",
  "pause mid-sentence",
  "clarifying tone",
  "confirming tone",
  "echoes statement",
  "repeats question",
  "soft rebuttal",
  "sharp rebuttal",
  "soft affirmation",
  "firm affirmation",
  "soft negation",
  "firm negation",
  "reluctant agreement",
  "eager agreement",
  "reluctant refusal",
  "eager refusal",
  "changes subject",
  "redirects",
  // Emotional shifts
  "tone shift",
  "mood change",
  "emotional outburst",
  "controlled outburst",
  "calming down",
  "getting heated",
  "building tension",
  "diffusing tension",
  "building anticipation",
  "releasing anticipation",
  "breaking down",
  "composing self",
  "rising clarity",
  "falling clarity",
  "dialogue crescendo",
  "dialogue decrescendo",
  "mood match",
  "mood clash",
  "beat change",
  // Interjections
  "interruptive gasp",
  "interruptive cough",
  "comic relief interjection",
  "dramatic interjection",
  "exasperated interjection",
  "gentle interjection",
  "harsh interjection",
  "humorous interruption",
  "serious interruption",
  "laughter break",
  "sob break",
  // Questioning
  "questioning tone",
  "rhetorical question",
  "loaded question",
  "innocent question",
  "echoing question",
  "probing question",
  "pressing",
  "probing",
  "interrogating",
  // Agreement/disagreement
  "affirming",
  "confirming",
  "validating",
  "contradicting",
  "challenging",
  "debating",
  "conceding",
  "yielding",
  "standing firm",
  // Asides
  "parenthetical aside",
  "metadialogue",
  "sidekick interrupts",
  "foil interrupts",
  "dialogue tag whisper",
  "dialogue tag shout",
  "sotto voce response",
  "shouted reply",
  "mock surprise",
  "real surprise",
  // Pauses in dialogue
  "clarifying pause",
  "reflective pause",
  "tension pause",
  "relief pause",
  "anticipatory pause",
];

const GENRE_TONE: string[] = [
  // Fantasy
  "fantasy",
  "high fantasy",
  "dark fantasy",
  "epic fantasy",
  "urban fantasy",
  "mythic fantasy",
  "sword and sorcery",
  "fairy tale",
  "fable",
  "legend",
  // Sci-fi
  "sci-fi",
  "space opera",
  "hard sci-fi",
  "soft sci-fi",
  "alien encounter",
  "first contact",
  "time travel",
  "parallel universe",
  "alternate history",
  "cyberpunk",
  "steampunk",
  "dieselpunk",
  "biopunk",
  "dystopian",
  "post-apocalyptic",
  "robot uprising",
  "AI rebellion",
  // Horror & Thriller
  "horror",
  "gothic horror",
  "cosmic horror",
  "supernatural horror",
  "body horror",
  "slasher",
  "zombie apocalypse",
  "monster story",
  "urban horror",
  "thriller",
  "psychological thriller",
  "crime thriller",
  "legal thriller",
  "political thriller",
  "eco-thriller",
  "cyber-thriller",
  "suspense",
  // Mystery
  "mystery",
  "detective noir",
  "whodunit",
  "cozy mystery",
  "locked room",
  "puzzle mystery",
  // Drama
  "drama",
  "melodrama",
  "tragedy",
  "tragicomedy",
  "historical drama",
  "family drama",
  "courtroom drama",
  "coming of age",
  "bildungsroman",
  "slice of life",
  "romance",
  "romantic drama",
  "love triangle",
  "sports drama",
  "political drama",
  "war drama",
  // Action & Adventure
  "action",
  "adventure",
  "swashbuckling",
  "quest",
  "epic journey",
  "exploration",
  "survival",
  "war epic",
  "military sci-fi",
  "spy thriller",
  "espionage",
  "heist",
  "pirate adventure",
  "sea voyage",
  "western",
  "spaghetti western",
  "revisionist western",
  "space western",
  "road trip",
  // Comedy
  "comedy",
  "dark comedy",
  "romantic comedy",
  "satire",
  "parody",
  "farce",
  "burlesque",
  "slapstick",
  "absurdist comedy",
  "camp comedy",
  // Paranormal
  "ghost story",
  "paranormal",
  "occult",
  "witch tale",
  "vampire story",
  "werewolf story",
  // Period & Style
  "medieval",
  "renaissance",
  "victorian",
  "noir",
  "film noir",
  "retro",
  "vintage",
  "period piece",
  "futuristic",
  "modern",
  "contemporary",
  "steampunk detective",
  "magical realism",
  "family-friendly",
  "young adult",
  "superhero",
  "vigilante",
  "antihero",
];

const EFFECTS_MODULATION: string[] = [
  // Voice processing
  "robotic",
  "robotically",
  "robotic modulation",
  "glitch",
  "glitchy",
  "digital distortion",
  "cybernetic glitch",
  "vocoder",
  "auto-tune",
  "pitch shifted",
  "harmonizer",
  "echo",
  "reverb",
  "delay",
  "robotic echo",
  "telephone filter",
  "radio broadcast",
  "megaphone",
  "speaking through mask",
  "muffled",
  "gagged",
  "underwater voice",
  "distant",
  "far away",
  "lo-fi",
  "hi-fi",
  "vinyl crackle",
  "walkie-talkie",
  "intercom",
  "two-way radio",
  "PA system",
  "loudspeaker",
  "stadium PA",
  "audiobook chassis",
  // Filter effects
  "low pass filter",
  "high pass filter",
  "bandpass",
  "filter sweep",
  "wah-wah",
  "flanging",
  "phasing",
  "chorus effect",
  "ring modulation",
  "tremolo effect",
  // Pitch effects
  "pitch shift up",
  "pitch shift down",
  "helium voice",
  "deep voice",
  "bass boost",
  "chipmunk",
  "slowed down voice",
  "detuned",
  "vibrato",
  "tremolo",
  // Distortion
  "bitcrushed",
  "corrupted",
  "fragmented",
  "data-corrupt",
  "chopped",
  "stuttered",
  "granular",
  "metallic",
  "metallic sheen",
  "tinny",
  "hollow",
  "hard clip",
  "soft clip",
  "digital clip",
  "bitrate drop",
  "sample rate reduction",
  "robotic stutter",
  "robotic sequence",
  // Signal types
  "sine wave tone",
  "square wave tone",
  "sawtooth tone",
  "white noise",
  "pink noise",
  "brown noise",
  "electric hum",
  "feedback",
  // Temporal
  "slow motion",
  "fast forward",
  "time stretch",
  "reversed",
  "looping",
  "syncopation",
  "waveform bend",
  // Spatial
  "surround sound",
  "stereo pan",
  "binaural",
  "close mic",
  "room mic",
  "ambient mic",
];

const TIME_MOOD_CONTEXT: string[] = [
  // Morning
  "calm morning",
  "brisk morning",
  "sleepy morning",
  "groggy morning",
  "peaceful morning",
  "energetic morning",
  "bright morning",
  "foggy morning",
  "rainy morning",
  "dewy morning",
  // Midday
  "sunny midday",
  "hazy midday",
  "rushed midday",
  "reflective midday",
  "bored midday",
  "creative midday",
  "anxious midday",
  "productive midday",
  "restless midday",
  "stressed midday",
  "focused midday",
  // Afternoon
  "lazy afternoon",
  "lethargic afternoon",
  "motivated afternoon",
  "stressed afternoon",
  "focused afternoon",
  "daydreaming afternoon",
  "nostalgic afternoon",
  "social afternoon",
  "introspective afternoon",
  "energetic afternoon",
  // Dusk
  "dusk calm",
  "dusk reflective",
  "dusk hopeful",
  "dusk sad",
  "dusk romantic",
  "dusk mysterious",
  "dusk weary",
  "dusk content",
  "dusk anticipatory",
  "dusk meditative",
  // Evening
  "evening relaxed",
  "evening upbeat",
  "evening playful",
  "evening flirtatious",
  "evening tired",
  "evening spirited",
  "evening mellow",
  "evening philosophical",
  "evening melodic",
  "evening dramatic",
  // Night
  "night introspective",
  "night dreamy",
  "night cautious",
  "night fearful",
  "night wistful",
  "night creative",
  "night solitary",
  "night serene",
  "night anxious",
  "night relieved",
  // Late night
  "late night tired",
  "late night determined",
  "late night nostalgic",
  "late night hopeful",
  "late night gloomy",
  "late night excited",
  // Dawn
  "early dawn hopeful",
  "early dawn quiet",
  "early dawn sleepy",
  "early dawn curious",
  // Situational - commute
  "rush hour tense",
  "rush hour impatient",
  "rush hour focused",
  "commute upbeat",
  "commute tired",
  "commute reflective",
  "commute frustrated",
  "commute content",
  // Situational - work
  "lunchtime hungry",
  "lunchtime cheerful",
  "lunchtime relaxed",
  "lunchtime rushed",
  "lunchtime casual",
  "midday crisis",
  "midday breakthrough",
  "workflow focused",
  "workflow productive",
  "workflow bored",
  "workflow challenged",
  "workflow creative",
  "deadline pressured",
  "deadline frantic",
  "deadline efficient",
  "deadline hopeful",
  "deadline stressed",
  "post-lunch sleepy",
  "post-lunch sluggish",
  "post-lunch motivated",
  "post-lunch creative",
  // Situational - general
  "midweek motivational",
  "midweek tired",
  "midweek energetic",
  "weekend relaxed",
  "weekend excited",
  "weekend ambitious",
  "weekend lazy",
  "weekend playful",
  "holiday mood",
  "celebration",
  "after hours",
];

// ---------------------------------------------------------------------------
// Build the master tag list
// ---------------------------------------------------------------------------

function buildTags(category: string, tags: string[]): AudioTag[] {
  return tags.map((tag) => ({ tag, category }));
}

export const V3_AUDIO_TAGS: AudioTag[] = [
  ...buildTags("Emotions", EMOTIONS),
  ...buildTags("Delivery & Direction", DELIVERY_DIRECTION),
  ...buildTags("Human Reactions", HUMAN_REACTIONS),
  ...buildTags("Sound Effects", SOUND_EFFECTS),
  ...buildTags("Accents & Dialects", ACCENTS_DIALECTS),
  ...buildTags("Pacing & Flow", PACING_FLOW),
  ...buildTags("Comedy & Performance", COMEDY_PERFORMANCE),
  ...buildTags("Narrative & Storytelling", NARRATIVE_STORYTELLING),
  ...buildTags("Character Archetypes", CHARACTER_ARCHETYPES),
  ...buildTags("Body States", BODY_STATES),
  ...buildTags("Environment & Atmosphere", ENVIRONMENT_ATMOSPHERE),
  ...buildTags("Dialogue", DIALOGUE_TAGS),
  ...buildTags("Genre & Tone", GENRE_TONE),
  ...buildTags("Effects & Modulation", EFFECTS_MODULATION),
  ...buildTags("Time & Mood Context", TIME_MOOD_CONTEXT),
];

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

const tagSet = new Set(V3_AUDIO_TAGS.map((t) => t.tag.toLowerCase()));

const categoryIndex = new Map<string, AudioTag[]>();
for (const tag of V3_AUDIO_TAGS) {
  const key = tag.category.toLowerCase();
  const arr = categoryIndex.get(key);
  if (arr) {
    arr.push(tag);
  } else {
    categoryIndex.set(key, [tag]);
  }
}

/**
 * Returns all tags in a given category (case-insensitive match).
 */
export function getTagsByCategory(cat: string): AudioTag[] {
  return categoryIndex.get(cat.toLowerCase()) ?? [];
}

/**
 * Returns true if the given string is a known v3 audio tag (case-insensitive).
 * Note: ElevenLabs v3 actually accepts free-form tags beyond this list,
 * but this validates against the known-good library.
 */
export function isValidV3Tag(tag: string): boolean {
  return tagSet.has(tag.toLowerCase());
}

/**
 * Search tags by substring match (case-insensitive).
 */
export function searchTags(query: string): AudioTag[] {
  const q = query.toLowerCase();
  return V3_AUDIO_TAGS.filter((t) => t.tag.toLowerCase().includes(q));
}

/**
 * Get a random selection of tags from a category.
 */
export function getRandomTags(category: string, count: number): AudioTag[] {
  const tags = getTagsByCategory(category);
  if (tags.length <= count) return [...tags];
  const shuffled = [...tags].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

// ---------------------------------------------------------------------------
// System prompt summary (condensed for injection)
// ---------------------------------------------------------------------------

export const V3_TAGS_SYSTEM_PROMPT_SUMMARY = `## ElevenLabs v3 Audio Tags Reference

Audio tags are placed in [square brackets] within speech text to control vocal delivery.
ElevenLabs v3 supports ~${V3_AUDIO_TAGS.length} tags across ${V3_TAG_CATEGORIES.length} categories. Key categories and examples:

**Emotions** (~${EMOTIONS.length} tags): [excited], [nervous], [frustrated], [sorrowful], [calm], [ecstatic], [bitter], [nostalgic], [mischievous], [contemplative]
**Delivery & Direction** (~${DELIVERY_DIRECTION.length} tags): [whispers], [shouts], [sarcastic], [commanding], [pleading], [matter-of-fact], [through gritted teeth], [sing-song], [monotone], [breathy]
**Human Reactions** (~${HUMAN_REACTIONS.length} tags): [laughs], [sighs], [gasps], [gulps], [clears throat], [crying], [snickers], [groans], [stammers], [hisses]
**Sound Effects** (~${SOUND_EFFECTS.length} tags): [applause], [gunshot], [explosion], [thunder], [door slam], [heartbeat], [footsteps], [record scratch], [sword clash], [fire crackling]
**Accents & Dialects** (~${ACCENTS_DIALECTS.length} tags): [British accent], [Southern US accent], [French accent], [pirate voice], [Australian accent], [Cockney accent], [Indian accent], [Russian accent]
**Pacing & Flow** (~${PACING_FLOW.length} tags): [pause], [rushed], [drawn out], [hesitates], [interrupts], [dramatic pause], [trailing off], [staccato], [slows down], [building]
**Comedy & Performance** (~${COMEDY_PERFORMANCE.length} tags): [deadpan delivery], [over the top], [campy], [villain voice], [announcer voice], [robot voice], [old person voice], [game show host]
**Narrative & Storytelling** (~${NARRATIVE_STORYTELLING.length} tags): [narrator], [voice-over], [dramatic reveal], [suspense build-up], [bedtime story], [noir narration], [inner monologue], [epic saga tone]
**Character Archetypes** (~${CHARACTER_ARCHETYPES.length} tags): [wizard], [detective], [pirate], [mad scientist], [ghost], [alien], [superhero], [butler]
**Body States** (~${BODY_STATES.length} tags): [shivering], [dizzy], [tired], [drunk], [out of breath], [jittery], [blushing], [heart racing]
**Environment & Atmosphere** (~${ENVIRONMENT_ATMOSPHERE.length} tags): [forest ambient], [city street], [haunted house], [cafe ambient], [spaceship interior], [cozy room]
**Dialogue** (~${DIALOGUE_TAGS.length} tags): [interrupts], [responds quickly], [corrects self], [tone shift], [questioning tone], [standing firm]
**Genre & Tone** (~${GENRE_TONE.length} tags): [noir], [horror], [comedy], [epic fantasy], [cyberpunk], [western], [romantic comedy]
**Effects & Modulation** (~${EFFECTS_MODULATION.length} tags): [robotic], [echo], [telephone filter], [muffled], [walkie-talkie], [pitch shifted], [lo-fi]
**Time & Mood Context** (~${TIME_MOOD_CONTEXT.length} tags): [calm morning], [rushed midday], [evening mellow], [late night nostalgic], [deadline pressure]

Tags can be combined: "[whispers][nervous] I think someone's watching us [gasps]"
Use sparingly — 1-3 tags per spoken segment for best results. Tags are free-form; this list covers known-effective tags but you can experiment with descriptive phrases.`;
