from __future__ import annotations

from pathlib import Path

TOOL_NAME = "aos-connectwise"
BACKEND_NAME = "connectwise-api"
MODE_ORDER = ["readonly", "write", "admin"]

CONNECTWISE_COMPANY_ID_ENV = "CW_COMPANY_ID_AUTH"
CONNECTWISE_PUBLIC_KEY_ENV = "CW_PUBLIC_KEY"
CONNECTWISE_PRIVATE_KEY_ENV = "CW_PRIVATE_KEY"
CONNECTWISE_SITE_URL_ENV = "CW_SITE_URL"
CONNECTWISE_BOARD_ID_ENV = "CW_BOARD_ID"
CONNECTWISE_COMPANY_ID_SCOPE_ENV = "CW_COMPANY_ID"
CONNECTWISE_TICKET_ID_ENV = "CW_TICKET_ID"
CONNECTWISE_CONTACT_ID_ENV = "CW_CONTACT_ID"
CONNECTWISE_PROJECT_ID_ENV = "CW_PROJECT_ID"
CONNECTWISE_CONFIGURATION_ID_ENV = "CW_CONFIGURATION_ID"

HARNESS_ROOT = Path(__file__).resolve().parents[2]
CONNECTOR_PATH = HARNESS_ROOT.parent / "connector.json"
PERMISSIONS_PATH = HARNESS_ROOT / "permissions.json"
